### ISSUE TITLE
In Show attachments, after deleted the attachment "No attachments available."  should be display

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2967] opened 2019-08-30 11:54 UTC
## Expected Behavior

In Show attachments, after deleted the attachment "No attachments available."  should be display

## Current Behavior

In Show attachments, after deleted the attachment "No attachments available."  should be display

## Screenshots (if appropriate):

![no attchments](https://user-images.githubusercontent.com/14290356/64018790-01852700-cb4b-11e9-8297-0166671d519d.png)

**Comment by sridhar391** [comment] 2019-08-31 06:38
@srileka We are closing this issue as we are not able to reproduce the issue and please feel free to re-open the issue if the issue reoccured

**Closed by sridhar391** 2019-08-31 06:38 UTC
