### ISSUE TITLE
Need option to remove (unused) label from board

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#185] opened 2016-02-05 08:44 UTC
From https://groups.google.com/forum/#!topic/restya/GgCN02Ea15g by Vicente Gonzalez

Is it possible to remove a label of a board? 

I want to remove a label which is not associated to any card.

**Comment by ssivachidambaram** [comment] 2016-02-18 12:44
Done.

**Comment by rrjanbiah** [comment] 2016-06-01 06:40
From Vicente Gonzalez in https://groups.google.com/forum/#!topic/restya/GgCN02Ea15g

> We have update to v 0.2.1 (2016-03-16) but we can't delete the labels. The process begins and returns OK but the labels still remains in our board.

So, reopening it now.

**Comment by lmarikannan** [comment] 2016-06-10 08:16
We have tried to reproduce this issue in http://boardalpha.demo.restya.com, but we cannot able to reproduce it. Closing this for now.

**Closed by lmarikannan** 2016-06-10 08:16 UTC
