### ISSUE TITLE
Blank Screen after using " I. Install script (Linux)"

### ISSUE THREAD

**Issue by githubkoma** [RestyaPlatform/board#628] opened 2016-05-04 10:04 UTC
Hi there,

i tried using the install-script provided at http://restya.com/board/install on a fresh Debian 8 and CentOS 7. The script itself went through fine i think, but when trying to open http://192.168.5.20/restyaboard/client/ i got the Website title "Restyaboard powered kanban board", but the page itself stayed White.

Do you have any suggestion here?

[restyaboard_install.txt](https://github.com/RestyaPlatform/board/files/248535/restyaboard_install.txt)

**Comment by rrjanbiah** [comment] 2016-05-04 11:31
@githubkoma 

Can you check developer console and find HTTP requests?

**Common issues:**

- 502 status usually means that php-fpm has not started
- 404 or 401 status usually means that database credentials are wrong. You may check further errors by enabling debug mode in https://github.com/RestyaPlatform/board/blob/master/server/php/config.inc.php#L15 and by checking HTTP response headers.

**Comment by githubkoma** [comment] 2016-05-04 14:13
Okay its working now, found some hints in the "restyaboard_install.log" that stated that imagemagick didnt install correctly. To get it installed GCC had to be used, which was not installed, and not caught by the install-script.

```
configure: error: in `/usr/local/src/imagick-2.2.2':
configure: error: no acceptable C compiler found in $PATH
```
But it didnt work out in the Long run, some more Errors occured..
```
[root@localhost]# less restyaboard_install.log | grep error
checking ImageMagick MagickWand API configuration program... configure: error: not found. Please provide a path to MagickWand-config or Wand-config program.
[root@localhost]#

```

So i had to install some packages manually (see below), and afterwards restya showed up normally..
```
yum install gcc
yum install -y ImageMagick ImageMagick-devel
yum -y install libpng-devel libjpeg-devel libtiff-devel
yum install php-pear
yum install php-pecl-imagick.x86_64
```

Some Sources i used:
https://gist.github.com/ARolek/9199329
http://www.electrictoolbox.com/install-php-pecl-centos/
http://www.linuxquestions.org/questions/linux-server-73/php-from-command-line-gives-a-warning-852811/
https://www.vultr.com/docs/install-imagemagick-on-centos-6
http://stackoverflow.com/questions/7073773/drop-postgresql-database-through-command-line

**Comment by rrjanbiah** [comment] 2016-05-04 14:42
@githubkoma Thanks a lot for your input. This is very helpful for us to fix it for all installs.

**Comment by lmarikannan** [comment] 2016-05-24 05:30
@githubkoma We tried in Ubuntu and CentOS, both checked in 32 and 64 bit version also. But we can not able to reproduce this. And we added php-pear installation code in CentOS script.

**Closed by lmarikannan** 2016-05-24 05:30 UTC
