### ISSUE TITLE
Copy card behavior is quirky 

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1913] opened 2018-07-09 08:37 UTC
## Current Behavior

1. When we copy a card with checklist, it is not updating without a page refresh
2. After sometime, another card without checklist is also getting creating

**Comment by sridhar391** [comment] 2018-07-20 10:36
We are unable to reproduce the issue on our dev server and it may be fixed by our some other code changes

**Closed by sridhar391** 2018-07-20 10:36 UTC
Labels: bug
