### ISSUE TITLE
Gmail addon and Upgrade problems

### ISSUE THREAD

**Issue by MFYDev** [RestyaPlatform/board#3331] opened 2019-11-04 16:57 UTC
Hi there, I cannot find out where can I set the SMTP. Now when I try to sign up a new customer, there is not any email I can receive.

And when I contact your support to add my url to the whitelist which will allow me to use Gmail addon, after 48 hours they told me they had already add it. Nothing happened, I still cannot use Gmail Addon and it display I am not on the whitelist.

Please help cause this is really important.

BTW, when will the next update? It has been about half an year.

## Expected Behavior
At least there should have a page where I can configure the SMTP right? But in the admin page I just saw IMAP configuration, where is SMTP configuration?

## Current Behavior
Cannot see SMTP configuration.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL): Ubuntu 18.04 LTS PHP 7.3 PostgreSQL 10
* Operating System and version (desktop or mobile): Both
* Link to your project: https://restya.fanyangmeng.com

**Comment by rrjanbiah** [comment] 2019-11-05 05:57
> Hi there, I cannot find out where can I set the SMTP. Now when I try to sign up a new customer, there is not any email I can receive.

Mails are handled using PHP and so if you have sendmail, you should receive email. 

For configuring custom SMTP, we use postfix approach (https://github.com/RestyaPlatform/board/issues/450#issuecomment-196814831) as we didn't want to bloat the codebase. Anyway there are some requests like  #1397 and we're considering for future release.

> And when I contact your support to add my url to the whitelist which will allow me to use Gmail addon, after 48 hours they told me they had already add it. Nothing happened, I still cannot use Gmail Addon and it display I am not on the whitelist.

Unfortunately changes to Gmail Addon is not reflecting and team is in contact with Google team. They'll keep you updated on this. 

> BTW, when will the next update? It has been about half an year.

Yes, we're hopefully in the final QA cycle and will update milestone by this week. For latest version you may pull from `dev` branch.

**Comment by FanyangMengDev** [comment] 2019-11-05 06:44
Wow, finnally!
But I still have a problem that actually I am a little bit confused that what to do when upgrade.
You said in your introduction that I need to overwrite the application files and add the script file to /sql/
What do you mean "overwrite the applictaion files"? Unzip the whole release files and overwrite the previous verison?
Then will I lose the data of my website? Or it has been saved in PostgreSQL and just overwrite the website root dictionary will not cause the data lose?
If just unzip and overwrite, that means every upgrade I should reconfigure the setting of some files right?
And last time, I suggest that I wanna use PostgreSQL to install, but now 0.6.7 just support PostgreSQL 10, so when 0.6.8 comes, is that mean I should uninstall verison 10 first? That will be super unconvinient and maybe cause some problems that both of us won't want.
Will you have a better solution of this circumstance? Or whne 0.6.8 coms you will give us a better instrution?
And the last question: When will you develop an Android APP? I use Android most, and if you make your APP up to the Google Play I will downliad it.
Thanks.

**Comment by FanyangMengDev** [comment] 2019-11-06 09:21
Hello？

**Comment by sridhar391** [comment] 2019-11-06 10:01
> Wow, finnally!
> But I still have a problem that actually I am a little bit confused that what to do when upgrade.
> You said in your introduction that I need to overwrite the application files and add the script file to /sql/
> What do you mean "overwrite the applictaion files"? Unzip the whole release files and overwrite the previous verison?

Yes, it will overwrite the previous version files

> Then will I lose the data of my website? Or it has been saved in PostgreSQL and just overwrite the website root dictionary will not cause the data lose?

Your Restyaboard data will be saved in the PostgreSQL database and the data will not be lost

> If just unzip and overwrite, that means every upgrade I should reconfigure the setting of some files right?
> And last time, I suggest that I wanna use PostgreSQL to install, but now 0.6.7 just support PostgreSQL 10, so when 0.6.8 comes, is that mean I should uninstall verison 10 first? That will be super unconvinient and maybe cause some problems that both of us won't want.

We have already given you the Restyaboard install script to install Restyaboard with PostgreSQL 12 and v0.6.8 (Roxette) will support the PostgreSQL version

> Will you have a better solution of this circumstance? Or when 0.6.8 comes you will give us a better instruction?

The Restyaboard v0.6.8 (Roxette) will handle the PostgreSQL 12

> And the last question: When will you develop an Android APP? I use Android most, and if you make your APP up to the Google Play I will download it.

Currently, we are not considering the idea of an Android app for Restyaboard.

**Comment by rrjanbiah** [comment] 2019-11-06 10:40
@FanyangMengDev 

Apologies for the delay. To add little more information to above note...

> And last time, I suggest that I wanna use PostgreSQL to install, but now 0.6.7 just support PostgreSQL 10, 

Restyaboard is fairly backward and forward compatible with most of the versions. So, it should already work with PostgreSQL 12. The problem is only with the install script and it will be addressed in Roxette version

> And the last question: When will you develop an Android APP? I use Android most, and if you make your APP up to the Google Play I will download it.

Restyaboard web app is already PWA and optimized for Android. Hence you can add it to your home screen and launch it more like an app.

**Comment by FanyangMengDev** [comment] 2019-11-06 12:05
Actually I just tried to use the dev archive file to update. And I met some problems.

1. I just download the dev archive file and unzip it, directly cut all the files in it to the website root dictionary and overwrite it. Then, I cannot log in my website anymore. That's my first question. What's the mean of application files, this really confused me so much.
2. Then, due to this circumstence. I use restyaboard_uninstall.sh first, when it says that it will remove the php, I choose yes. You know, when installed restya board, your script install php 7.2. Actually my server has already used php 7.3, which just not in the same dictionary. Then the script remove the php 7.2, and I can see that it scaned php 7.3, which made me so afraid that it will delete it too (finally I found that it won't). So the point is, why don't you cannot just use the php which the server already has? Or update the default php version to 7.3. I mean, the newer version it is, the safer it is right?
3. After uninstall it, I reinstall again by using the script you gave me last time which allow user use PSQL 12, and I just got 0.6.7 again.

So after going through these, I lost all of my data(fortunately I did not have so much data), just tried a failed upgrade. Would you please add a upgrade wiki page which has more information about what  we should do if we wanna use dev branch?

At the same time, could you please tell me, where did I do wrong when I tried to use dev branch to implement an upgrade? It will be so much appreciate. 

And one more question, have you made any progress about contacting with Google about Gmail Addon? I really wanna use it but it has been more than a week, I still be told that my URL is not on the whitelist.

Thank you so much for all you guys support and hardworking. You are always the best.

**Comment by FanyangMengDev** [comment] 2019-11-06 12:25
Oh, have to ask one more question, the Chinese simplified tranlation is really bad. Where can I contribute my own translation to you?

**Comment by sridhar391** [comment] 2019-11-06 13:16
@FanyangMengDev Please contribute your Chinese translation at https://www.transifex.com/restya/restyaboard

**Comment by FanyangMengDev** [comment] 2019-11-06 13:38
@sridhar391 OK, could you please answer my former question?

**Comment by FanyangMengDev** [comment] 2019-11-07 06:45
Hello?
The php version is the most important thing. Cause when I try to install reatyaboard, it asked me that whether I wanna install php, I choose yes because I thought maybe it will only works well under the version in your script. But actually with the default php 7.3 it works well too, when I reboot the server it change the default php fo version 7.2 which makes me cannot use composer, I searched for long time to figure it out how to change default php version to 7.3. After switch to it, all works well. So I really think that before your script install, it can scan that whther users have php, it

**Comment by FanyangMengDev** [comment] 2019-11-07 06:46
wrong click about closing the issue, reopen it again.
Please answer me, looking forward to your answer.

**Comment by sridhar391** [comment] 2019-11-07 11:30
@FanyangMengDev We are cresting the document for how jto 

> @rrjanbiah @sridhar391
> **Thank you so much for your answer first.**
> 
> Actually last moment I just tried to use the dev archive file to upgrade. And I met some problems.
> 
> Here is what I did in the following:
> 
> 1. I just download the dev archive file and unzip it, **directly cut all the files in it to the website root dictionary and overwrite it**. Then, I cannot log in my website anymore. That's my first question. **What's the meaning of application files**, this really confused me so much.
> 2. Then, due to this circumstence. I use restyaboard_uninstall.sh first, when it says that it will remove the php, I choose yes. You know, when installed restya board, your script install php 7.2. Actually my server has already used php 7.3, which just not in the same dictionary. Then the script remove the php 7.2, and I can see that it scaned php 7.3, which made me so afraid that it will delete it too (finally I found that it won't). **So the point is, why don't you just use the php which the server already has? Or update the default php version to 7.3. I mean, the newer the version, the safer it is right?**
> 3. After uninstall it, I reinstall again by using the script you gave me last time which allow user use PSQL 12, and I just got 0.6.7 again.
> 
> So after going through these, I lost all of my data ( fortunately I did not have so much data ), just tried a failed upgrade.
> 
> **Would you please add a upgrade wiki page which has more information about what we should do if we wanna use dev branch to upgrade? I strongly recommend this because I think not just me wanna to try the newest function and give you guys feedback.**

We are creating the document for how to build the deploy files from the dev branch 

> At the same time, could you please tell me, **where did I do wrong when I tried to use dev branch to implement an upgrade?** It will be so much appreciate.
> 
> **Thank you so much for all you guys support and hardworking. You are always the best.**

In the dev branch, there are core files, you just only need the deploy files to install the Restyaboard

**Comment by rrjanbiah** [comment] 2019-11-14 05:37
*Internal note*

Reply from Gmail team (finally):

We are still investigating this issue. Sorry for the delay. This may be an issue with the G Suite Marketplace SDK rather than with Gmail Add-ons itself. What is the expected behavior of the new deployment compared to the old deployment?

**Comment by sridhar391** [comment] 2019-11-14 13:06
@FanyangMengDev Please refer the attached document for building the latest deploy files from the dev branch
[Build Restyaboard files from Github Repository dev branch.pdf](https://github.com/RestyaPlatform/board/files/3846588/Build.Restyaboard.files.from.Github.Repository.dev.branch.pdf)

**Comment by sridhar391** [comment] 2021-04-08 12:52
@MFYDev Due to inactivity, we are closing this issue, if the issue occurred again, please feel free to reopen the issue

**Closed by sridhar391** 2021-04-08 12:52 UTC
