### ISSUE TITLE
When I press at the board Ctrl + C card going to archive

### ISSUE THREAD

**Issue by ssivachidambaram** [RestyaPlatform/board#580] opened 2016-04-12 10:26 UTC

**Comment by lmarikannan** [comment] 2016-04-25 05:23
We cannot able to reproduce this.

**Comment by Pablissimo** [comment] 2016-05-11 11:05
Appreciate this is closed but it's a real issue - I'm also seeing this behaviour:

- Browser: Chrome 50.0.2661.94 m (doesn't reproduce in IE11, unsure about others)
- Add a card to any board
- Click to open the card
- Triple-click the '[Name] added [Card name] to list "[List name]" text to select-all (this seems the most reliable way to make it happen)
- Hit Ctrl-C
- Card archives, instead of copying the highlighted text

I can also do this by just drag-selecting text as shown in the below animation:

![archiving](https://cloud.githubusercontent.com/assets/1470336/15178895/6c3a9acc-1770-11e6-8073-32ae723bcd0a.gif)

**Comment by rrjanbiah** [comment] 2016-05-11 12:47
@Pablissimo Many thanks for your note and screencast. Reopening it now.

**Comment by ssivachidambaram** [comment] 2016-05-12 14:16
@Pablissimo We have tried to reproduce this issue in browser: chrome 50.0.2661.102 m, OS: Windows 8.1 and we pressed Ctrl + C, but we cannot able to reproduce it. Can you please mention your OS?

**Comment by Pablissimo** [comment] 2016-05-12 16:18
Windows 7 Enterprise 64-bit SP1.

It might actually be a side-effect of how I'm bashing Ctrl-C, I think it's probably a timing thing where the C key is being held down longer than the Ctrl.

This works fine:

* Select text
* Hold Ctrl
* Tap C
* Release Ctrl

This breaks:

* Select text
* Hold Ctrl
* Hold C
* Release Ctrl, then release C
* Card archives

That second flow sounds mad, but it's probably not too uncommon if you're a touch-typist - in Windows apps you'd typically get a quarter of a second or so's grace before the application receives another C key-up. For example, try this:

* Open Notepad
* Type some text
* Select some of the text
* Hold Ctrl-C - note that the text remains selected
* Watch carefully, and release Ctrl while keeping C held - the selected text is replaced with an ever-increasing number of c characters but only after a short delay

It's as though whatever hotkey plugin being used doesn't do that suppression, or sees a Ctrl-C to C transition as being another key-up event for the C key - will try and repro at home this weekend

**Comment by rrjanbiah** [comment] 2016-05-12 17:19
@Pablissimo Wow. Many thanks for your helpful note.

**Comment by lmarikannan** [comment] 2016-06-01 10:39
Fixed in dev branch

**Comment by lmarikannan** [comment] 2016-06-10 07:10
Closing this for now.

**Closed by lmarikannan** 2016-06-10 07:10 UTC
