### ISSUE TITLE
error during update to 0.4.2 on debian 8.7

### ISSUE THREAD

**Issue by aleromano89** [RestyaPlatform/board#1126] opened 2017-03-20 09:01 UTC
[restyaboard_install.zip](https://github.com/RestyaPlatform/board/files/854284/restyaboard_install.zip)

My current version of restya is 0.3 and I'm trying to update to 0.4.2 by install script restyaboard.sh.

I have attached here my install log.
How can I solve?

**Comment by lmarikannan** [comment] 2017-03-21 12:06
@aleromano89  We have tried to reproduce this issue in local but we cannot able to reproduce it. 

Can you please check `release` file is exist on your server folder `/opt/restyaboard/`? If it is not exist then replace this file [release.txt](https://github.com/RestyaPlatform/board/files/858016/release.txt) into `/opt/restyaboard/`. And remove the file format `.txt`. Then check again.

And you need to execute the below sql files manually for sql changes, 
- https://github.com/RestyaPlatform/board/blob/master/sql/upgrade-0.3-0.4.sql
- https://github.com/RestyaPlatform/board/blob/master/sql/upgrade-0.4-0.4.1.sql

**Comment by aleromano89** [comment] 2017-03-21 13:15
When should I execute sql? before update or after update?

**Comment by lmarikannan** [comment] 2017-03-21 13:35
@aleromano89 need to execute sql after update

**Comment by aleromano89** [comment] 2017-03-21 13:35
the file `release` was already existent, its content was v0.4.2. Anyway I have tried to replace it with one you attached in the previous post. And I have tried again to execute sh.
This is the install log


[upgrade-0.3-0.4.sql.zip](https://github.com/RestyaPlatform/board/files/858254/upgrade-0.3-0.4.sql.zip)

**Comment by lmarikannan** [comment] 2017-03-21 15:17
@aleromano89, Can you please replace below changes in your `restyaboard.sh` file and check again?

On line number : https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh#L204

```
        if [ -f "$DOWNLOAD_DIR/release" ];
	then
		version=$(cat ${DOWNLOAD_DIR}/release)
		if [[ $version < $RESTYABOARD_VERSION ]];
		then
			update_version
			exit
		else
			echo "No new version available"
			exit;
		fi
	else
```

**replace below** 
       
```
        if [ -f "$DOWNLOAD_DIR/release" ];
	then
		update_version
		exit
	else
```

**Comment by aleromano89** [comment] 2017-03-22 10:19
thanks, now from the page "about" restya version seems to be 0.4.2, but in the install log I yet see some errors.(nevertheless  restya platform is yet working) 
Anyway I have already executed sql commands after install.

[restyaboard_install.zip](https://github.com/RestyaPlatform/board/files/861071/restyaboard_install.zip)

**Comment by lmarikannan** [comment] 2017-03-22 12:05
@aleromano89 Currently there is no sql file in 0.4.2 version, so that only some errors are displayed. So that is not an issue. Closing this for now. If you get any issues, please feel free to reopen.

**Closed by lmarikannan** 2017-03-22 12:05 UTC
