### ISSUE TITLE
API function /users/?/cards does not work

### ISSUE THREAD

**Issue by maxhq** [RestyaPlatform/board#1509] opened 2018-01-30 19:57 UTC
Cards of a certain user cannot be retrieved using the API call (e.g. via `/api_explorer` and a valid token). The returned array is always empty.

I tried it with an admin token and a user token (trying to get a list of my own cards).

## Your Environment
- Version used: v0.6
- Environment: Debian Stretch (Docker), PHP 7.0.19-1, PostgreSQL 9.6

**Comment by sridhar391** [comment] 2018-01-31 10:37
@maxhq Cannot able to Reproduce the Issue

[user_cards.webm.zip](https://github.com/RestyaPlatform/board/files/1681300/user_cards.webm.zip)

**Comment by sridhar391** [comment] 2018-01-31 10:39
@maxhq Can you please provide us the steps to reproduce the issue

**Comment by lmarikannan** [comment] 2018-02-05 13:07
@maxhq We're waiting for your reply

**Comment by sridhar391** [comment] 2018-02-13 11:23
@maxhq we are closing this issue currently. if the issue still exists please reopen this issue

**Closed by sridhar391** 2018-02-13 11:23 UTC
Labels: bug

**Comment by maxhq** [comment] 2018-02-19 15:47
@sridhar391 Thank you very much for the screencast and sorry for my late answer, I was quite busy.
I followed your steps and still get an empty list.
In the attached screencasts you can see how I log in with test user joe@example.org (ID: 6) who owns two cards. But then I get no results via API.

[screencast.zip](https://github.com/RestyaPlatform/board/files/1737352/screencast.zip)

**Comment by lmarikannan** [comment] 2018-02-21 06:32
@maxhq Sorry for that, actually `/api/v1/users/?/cards.json` API will list only assigned cards for the particular user. In your video, those two cards are created by `joe@example.org`, but those cards are not assigned to that particular user, that means `joe@example.org` is not member of those cards. So only that  `/api/v1/users/?/cards.json` API listed empty response. This  `/api/v1/users/?/cards.json` API call is used on user's profile page Cards tab.
