### ISSUE TITLE
Enhancing the Permissions

### ISSUE THREAD

**Issue by olympica** [RestyaPlatform/board#2760] opened 2019-08-06 18:32 UTC
This is something I thought I would mention here as it could be really useful.
is there a way we could add an option in the permission to give the administrators an option to let certain users edit/view only cards that are assigned to them?
For example, if I add somebody to a board as a view only user, I would only want them to be able to view certain cards that are related to them and not the other cards. so in the board lists, They can only see the cards that they are a member of. This means they wouldn't be able to view the status/placement of any other card.  
Thanks,

**Comment by dfanaei** [comment] 2019-08-15 16:53
This feature would be amazing. This could get Restyaboard to stand out against most of the big guys like Trello. I have not seen any other kanban board have this feature. The funny thing is this is a feature that any team will certainly use but yet none of the apps out there have this implemented. My development skills aren't at that level yet, otherwise, I would have helped implementing this one.

**Comment by rrjanbiah** [comment] 2019-08-15 19:01
@olympica @dfanaei

Currently users can filter card assigned to them and self assign any open cards. 

If possible, please share where your use cases will be used.

**Comment by rrjanbiah** [comment] 2019-08-15 19:07
*Internal note*

Possible duplicate of #2023

**Comment by olympica** [comment] 2019-08-15 19:21
@rrjanbiah having a filter option is cool, However, as a team, sometimes the management would want some team members to only have access (whether if its view only or edit) to the cards that they have been assigned to. 
For example: If A is a manager and B is a regular user. 
A would make cards in the board for all users, but B only sees the cards that are assigned to him. 

Sometimes you won't want other people to see the cards that are not assigned to them so they can only focus on what they are supposed to be doing. 

My last team actually quit using trello for this reason and started using another opensource app ( they had to customize the codes in order to get this working). I have also heard many people that manage a team asking for a feature like this.

**Comment by olympica** [comment] 2019-08-15 19:34
Also, Just so you can see the team management psychology behind why this feature could be really useful: 
usually when a project is to meet a deadline, team members seem to be competitive with each other at times. This is usually good but in some cases is the opposite. 
if a team member has a set of tasks to finish and is perhaps overwhelmed by the amount of work, they usually look around to compare themselves to other members and see how fast they are doing. now, If one team member is lacking of being organized to meet deadlines on his tasks, the situation will affect everyone else in the team therefore the others would also not take their tasks serious enough and it will lead to failure of the whole project. This is why this is a really important feature that some teams need.

**Comment by rrjanbiah** [comment] 2019-08-16 06:09
@olympica Thanks a lot for your explanation. I hope, with current roles, it should be possible. Anyway, we'll check internally and update you.

**Comment by sridhar391** [comment] 2020-06-10 09:36
Use cases

- If the user adds the card with self assign only, the card should be shown
- In the live updation also, need to check if the permission is enabled or not and
- while importing the cards, need to check the permission and show only assigned cards
- While converting the checklist item to the card, need to self assign inorder to see the card
- While adding the card with card template, member should be self assigned
- While adding the card via instant add card, self assigned card only be shown
- While copying the card, need to copy the members or the copied card should not be shown
- While copying the list and moving the list, self assigned cards only should be shown
- While copying the board, the self assigned cards only to be shown

**Comment by rrjanbiah** [comment] 2020-08-11 18:03
*Based on internal discussion...*

1. Have to add one `Restricted` board level role. This access will all access or the `Editor` role--except 'Add Card' and only assigned tasks.
2. The assumption here is that the cards will be added by `Owner` or `Editor` level users and these `Restricted` level users will only view and work only on their cards. Hence, `Restricted` users can't create cards too.
3. So, above https://github.com/RestyaPlatform/board/issues/2760#issuecomment-641881861 use cases are all void.

**Closed** 2020-12-10 13:20 UTC
Labels: enhancement

**Comment by sridhar391** [comment] 2021-04-05 08:39
We have added the documentation to explain about the feature in the link https://restya.com/board/docs/restyaboard-set-up-permissions-to-show-assigned-cards-only/
