### ISSUE TITLE
Ubuntu 15.04

### ISSUE THREAD

**Issue by FilewalkerLuke** [RestyaPlatform/board#786] opened 2016-08-31 20:13 UTC
I think my Server isn´t running the script correct. I get this in console when I run it:

++ whoami
root
+++ cat /etc/issue
++ echo Ubuntu 15.04 '\n' '\l'
Ubuntu 15.04 \n \l
+++ sed 's/^._Ubuntu._$/Ubuntu/g'
+++ sed 's/^._Debian._$/Debian/g'
+++ grep 'Ubuntu|Debian|Raspbian'
+++ sed 's/^._Raspbian._$/Raspbian/g'
+++ sed 's/^._Debian._$/Debian/g'
+++ cat /proc/version
++ OS_REQUIREMENT=
++ '[' '' = Ubuntu ']'
++ '[' '' = Debian ']'
++ '[' '' = Raspbian ']'
++ yum install -y curl unzip
./restyaboard.sh: line 23: yum: command not found
+++ sed -e 's/[^v0-9.]//g'
+++ awk '{print $2}'
+++ grep tag_name -m 1
+++ curl --silent https://api.github.com/repos/RestyaPlatform/board/releases
./restyaboard.sh: line 25: curl: command not found
++ RESTYABOARD_VERSION=
++ POSTGRES_DBHOST=localhost
++ POSTGRES_DBNAME=restyaboard
++ POSTGRES_DBUSER=restya
++ POSTGRES_DBPASS='hjVl2!rGd'
++ POSTGRES_DBPORT=5432
++ EJABBERD_DBHOST=localhost
++ EJABBERD_DBNAME=ejabberd
++ EJABBERD_DBUSER=ejabb
++ EJABBERD_DBPASS=ftfnVgYl2
++ EJABBERD_DBPORT=5432
++ DOWNLOAD_DIR=/opt/restyaboard
++ '[' -d /opt/restyaboard ']'
++ set +x
Is Restyaboard already installed y/n?
n
++ case "${answer}" in
++ '[' '' = Ubuntu ']'
++ '[' '' = Debian ']'
++ '[' '' = Raspbian ']'
++ set +x
Setup script will install version  and create database restyaboard with user restya and password hjVl2!rGd. To continue enter "y" or to quit the process and edit the version and database details enter "n" (y/n)?
y
++ case "${answer}" in
++ echo 'Checking nginx...'
Checking nginx...
++ which nginx
++ echo 'Checking PHP...'
Checking PHP...
++ hash php
++ echo 'Installing PHP fpm and cli extension...'
Installing PHP fpm and cli extension...
++ yum install -y php-fpm php-devel php-cli
./restyaboard.sh: line 959: yum: command not found
++ '[' 127 '!=' 0 ']'
++ echo 'php-devel installation failed with error code 21'
php-devel installation failed with error code 21
++ exit 1

What am I doing wrong?

Thanks
BR

**Comment by lmarikannan** [comment] 2016-09-02 06:10
@FilewalkerLuke We have tried to reproduce this issue in local but we cannot able to reproduce it. Can you please double check that?

**Comment by lmarikannan** [comment] 2016-09-19 12:44
@FilewalkerLuke We're waiting for your reply

**Comment by lmarikannan** [comment] 2016-10-18 11:44
@FilewalkerLuke Actually install script doesn't find your server OS using `/proc/version`, so we have added additional check in `/cat/issue` file to find OS in this commit https://github.com/RestyaPlatform/board/commit/419d011d1fce5d30d3c4f59963ba6ad891d81a5f.

**Comment by rrjanbiah** [comment] 2016-10-18 12:09
Reopened. Refer to clean code from @BlackDuck888 https://github.com/BlackDuck888/board/blob/906dd469bd6d24431a469aa7ed33501aac7e5374/install/restyaboard_apache.sh#L17

**Comment by lmarikannan** [comment] 2016-11-07 06:53
Fixed in this commit https://github.com/RestyaPlatform/board/commit/ea4be408de7ee4c03414ab82751dfed98737e576

**Closed by lmarikannan** 2016-11-07 06:53 UTC
