### ISSUE TITLE
Timezone respected when storing time but not rendering time

### ISSUE THREAD

**Issue by andrewperry** [RestyaPlatform/board#1942] opened 2018-07-12 09:23 UTC
I am based in Australia (GMT+10 timezone)

In many places the system shows that an action I just took happened 10 hours ago, when I only just did it.

It looks like the Timezone preference in my profile is not being applied correctly when displaying times since something was done in the activity feed.

**Comment by sridhar391** [comment] 2018-07-12 09:52
Can you please change your `Site Timezone` in your Restyaboard which will be in `http://your_restyaboard_url/#/settings`

**Comment by andrewperry** [comment] 2018-07-23 05:46
This should be reopened as I had already set that Timezone on the server and yet the UI is showing the wrong thing.

**Comment by andrewperry** [comment] 2018-07-23 06:45
@sridhar391 I don't seem to have permission to re-open it.

**Comment by andrewperry** [comment] 2018-07-23 07:35
![screenshot-5](https://user-images.githubusercontent.com/94937/43063239-a90ce7be-8e9e-11e8-963c-1f3f647c4cc7.jpg)
![screenshot-6](https://user-images.githubusercontent.com/94937/43063240-a94a5946-8e9e-11e8-8526-9fe09fd0d504.jpg)

These are examples of how the UI is showing things done just an hour or two ago, when the system settings are:

![screenshot-7](https://user-images.githubusercontent.com/94937/43063332-d8e4bc82-8e9e-11e8-82a8-d7d42154910b.jpg)

**Comment by sridhar391** [comment] 2018-07-23 07:41
Please provide screenshots for reproducing the issue

**Comment by andrewperry** [comment] 2018-07-23 07:43
See screenshots above.

**Comment by sridhar391** [comment] 2018-07-25 06:14
Can we have screen share meeting to solve the issue

**Comment by sridhar391** [comment] 2018-10-01 04:57
Closing the issue due to inactivity

**Closed by sridhar391** 2018-10-01 04:57 UTC

**Comment by batara666** [comment] 2022-03-19 03:08
I have exactly same problem

current GMT+7 TIME IS

19 Mar 2022 10:07

then I try to send a comment

It's shows as 18 Mar 2022 21:07

**Comment by sridhar391** [comment] 2022-03-21 05:05
@batara666 Can you please tell us if you have set the Site Timezone in the admin panel settings page under the user tab like the attached image "system_site_timezone.png" and please tell us if the user set his local timezone in the user profile settings page like the attached image "user_timezone.png"

![system_site_timezone](https://user-images.githubusercontent.com/17172525/159207879-38254308-32df-47b2-8967-8f8258e62ce9.png)

![user_timezone](https://user-images.githubusercontent.com/17172525/159207892-bdd35b15-0d9b-4441-aa13-73996ed9871f.png)
