### ISSUE TITLE
No Organizations Available

### ISSUE THREAD

**Issue by ktdmedia** [RestyaPlatform/board#84] opened 2015-10-13 09:37 UTC
When clicking Organizations button as an admin it displays correctly. As a user, "No organizations available."  for any board not created by that user.

Installed using docker, ubuntu 14.04.

**Comment by ktdmedia** [comment] 2015-10-13 09:44
When you visit the Organization manually "/#/organization/9" it works fine.

**Comment by rrjanbiah** [comment] 2015-10-13 11:56
@srileka Kindly try to reproduce

**Comment by srileka** [comment] 2015-10-13 14:47
Could you check whether the organization is a Public or Private? If it is public organization you can view those boards.

**Comment by rrjanbiah** [comment] 2015-10-13 15:21
@ktdmedia Can we have your comment on @srileka note, please?:

> Could you check whether the organization is a Public or Private? If it is public organization you can view those boards.

**Comment by ktdmedia** [comment] 2015-10-13 23:55
@rrjanbiah @srileka - The permission setting has no effect on the error. It occurs even if the Organization is Public.

**Comment by rrjanbiah** [comment] 2015-10-14 13:06
@ktdmedia Thanks for your report. It seems to be related to https://github.com/namikingsoft/docker-restyaboard/issues/2#issuecomment-147890744 Can you please check and confirm?

**Comment by mishio** [comment] 2015-12-09 08:17
I get this problem too (v0.1.5 on Ubuntu) though it doesn't seem to happen on your demo site.

Not sure if "/#/organization/9" works though, it sends me to #/boards.

**Comment by ssivachidambaram** [comment] 2015-12-24 05:39
Fixed in v0.1.6.

**Closed by ssivachidambaram** 2015-12-24 05:39 UTC
