### ISSUE TITLE
Any chance to create user from console?

### ISSUE THREAD

**Issue by lgg** [RestyaPlatform/board#1542] opened 2018-02-09 05:36 UTC
relative to #1541

Until there is no cli in RestyaBoard - are there any other methods for creating user from console?

**Comment by sridhar391** [comment] 2018-02-09 08:15
@lgg we already have web interface for creating user
1. Login as admin and click admin
![admin](https://user-images.githubusercontent.com/17172525/36017175-99596b86-0d9c-11e8-8dd0-1e1cdcc1436d.png)
2. Click users for users page
![users](https://user-images.githubusercontent.com/17172525/36017179-9c7b0176-0d9c-11e8-9cda-5d8cab02a508.png)
3. Click Add User for creating user
![add_user](https://user-images.githubusercontent.com/17172525/36017823-58132a60-0d9f-11e8-9ae5-11597183f321.png)
4. Then give the user credential for creating user
![user_add](https://user-images.githubusercontent.com/17172525/36017856-70dbf5f4-0d9f-11e8-9da1-4141878e1415.png)


Are you suggesting to use  command line interface tools for creating users

**Comment by lgg** [comment] 2018-02-09 16:18
@sridhar391 i mean from unix/ssh console, not from web-ui.

**Comment by rrjanbiah** [comment] 2018-02-28 10:53
Duplicate of #1541

**Closed by rrjanbiah** 2018-02-28 10:53 UTC
Labels: duplicate, enhancement
