### ISSUE TITLE
LDAP passwords containing £ symbol not accepted

### ISSUE THREAD

**Issue by Gloompirate** [RestyaPlatform/board#695] opened 2016-06-23 11:58 UTC
Hi,

One of our users has a password that contains a £ symbol. When trying to authenticate via LDAP into restyaboard, he is unable to login. Once he has changed his password to remove the £ symbol he is able to login successfully.

I have also created a test account to try other symbols in the password, and the only one that causes the issue is the £ symbol. 

I guess that in the password field the £ symbol is not being encoded correctly.

Thanks.

**Comment by rrjanbiah** [comment] 2016-06-23 12:27
@Gloompirate Thanks for your report. We'll fix it.

**Comment by lmarikannan** [comment] 2016-10-18 15:43
@Gloompirate We tried in our local, But we can not able to reproduce this. Without using `utf8_decode()` function also it's working fine here. So please check your LDAP configuration settings are setting properly on http://{{your_domain_name}}/#/settings/2 . Closing this for now. If you get any issues, please feel free to reopen with more information.

**Closed by lmarikannan** 2016-10-18 15:43 UTC
