### ISSUE TITLE
After Install white screen

### ISSUE THREAD

**Issue by superjuve** [RestyaPlatform/board#685] opened 2016-06-14 13:52 UTC
Hi, I already installed Restyaboard.

When I put adress I have favicon and Meta name alright. But site is blank.
In attachment is install.log but its in Czech language. I can translate everything.

[restyaboard_install.txt](https://github.com/RestyaPlatform/board/files/314069/restyaboard_install.txt)

![problem](https://cloud.githubusercontent.com/assets/19925380/16045268/fc410c68-3247-11e6-8448-41e2c67a1686.png)

**Comment by rrjanbiah** [comment] 2016-06-14 15:01
@superjuve Looks like both `php` and `php-fpm` are not installed. Can you please try to install them manually again and retry?

**Comment by superjuve** [comment] 2016-06-14 19:26
@rrjanbiah I install everything from script.

I found a lot of ways how install php and php-fpm, are these basic correct?
```
sudo apt-get install php5 
sudo apt-get install php5-fpm
```

**Comment by rrjanbiah** [comment] 2016-06-15 12:40
@superjuve Were you able to figure out the issue? Probably, you're using any different distribution?

**Comment by DavidJares** [comment] 2016-06-15 12:44
Hello, I can't install apt-get install php5:
root@MYSERVER:/etc/nginx# apt-get install php5-fpm
Načítají se seznamy balíků… Hotovo
Vytváří se strom závislostí       
Načítají se stavové informace… Hotovo
Některé balíky nemohly být instalovány. To může znamenat, že požadujete
nemožnou situaci, nebo, pokud používáte nestabilní distribuci, že
vyžadované balíky ještě nebyly vytvořeny nebo přesunuty z Příchozí fronty.
Následující informace vám mohou pomoci vyřešit tuto situaci:

Následující balíky mají nesplněné závislosti:
 cron : Závisí na: libpam0g (>= 0.99.7.1) ale nebude se instalovat
        Závisí na: adduser ale nebude se instalovat
        Závisí na: libpam-runtime (>= 1.0.1-11) ale nebude se instalovat
 default-jre-headless : Závisí na: openjdk-8-jre-headless ale nebude se instalovat
 dpkg : Porušuje: php5-fpm (< 5.6.4+dfsg-3~) ale 5.4.45-0+deb7u3 se bude instalovat
 init-system-helpers : Závisí na: perl-base (>= 5.20.1-3) ale nebude se instalovat
                       Koliduje s: file-rc (< 0.8.17~) ale 0.8.15 se bude instalovat
 libreadline6 : Závisí na: readline-common ale nebude se instalovat
 libssl1.0.0 : Závisí na: debconf (>= 0.5) ale nebude se instalovat nebo
                            debconf-2.0
 libuuid1 : Závisí na: passwd
            Doporučuje: uuid-runtime
 php5-fpm : Závisí na: php5-common (= 5.4.45-0+deb7u3) ale nebude se instalovat
            Závisí na: ucf ale nebude se instalovat
            Závisí na: tzdata ale nebude se instalovat
E: Chyba, pkgProblemResolver::Resolve vytváří poruchy, to může být způsobeno podrženými balíky.

**Comment by rrjanbiah** [comment] 2016-06-15 13:07
@DavidJares Did you update any PPA?

Can you please try below links and see if they're helpful?

- http://askubuntu.com/questions/140246/how-do-i-resolve-unmet-dependencies-after-adding-a-ppa
- http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html#instgde-prereq-php56-install-ubuntu

**Comment by DavidJares** [comment] 2016-06-15 13:32
It seems like the problem is in PHP7 (need php5-fpm to run Restya)

**Comment by DavidJares** [comment] 2016-06-15 15:17
I found the issue. It is lame and I would like to express my thanks for all help. My friend installed PHP in unusual place, so i needed just to add `fastcgi_pass    unix:/var/run/php/php7.0-fpm.sock;` on 35th line of `restyboard.conf`. Now it seems like everything is working.

**Comment by rrjanbiah** [comment] 2016-06-15 15:22
@DavidJares Awesome. Glad to know that.

@superjuve Do you find @DavidJares note helpful for you?

**Comment by lmarikannan** [comment] 2016-10-24 07:21
Fixed in this commit https://github.com/RestyaPlatform/board/commit/14c8d56818098b3ed56709e419d8e04ab29a3e44, https://github.com/RestyaPlatform/board/commit/d0356b2231c061b6c8adc804f691de0e63937f2b

**Comment by Polycris** [comment] 2016-11-03 14:04
Hi, guys! 
I've been tried to install restya on my server Ubuntu 16.04.1 LTS and I also had problems with php7.0-fpm. I've tryed to execute the script that  upgraded to PHP 7, posted by lmarikannan (commit 14c8d56) and I've saw that another error has been ocurred when execute the command at line 307:
 apt-get install -y php7.0-imagick

I've solved following the instruction recommended on http://askubuntu.com/questions/769396/how-to-install-imagemagick-for-php7-on-ubuntu-16-04
apt-get install -y php-imagick
 
could you fix the script with this command?

Poly

**Comment by rrjanbiah** [comment] 2016-11-03 14:15
@Polycris Thanks for your report and note

**Comment by Polycris** [comment] 2016-11-10 12:59
After a lot of problems with dependencies and with my local proxy, I got finish the script install... but site is also blank. I've already set the php7.0-fpm on restyaboard.conf file, but doesn't works. 
What else can I do? 
Poly


[restyaboard_install.log.txt](https://github.com/RestyaPlatform/board/files/583383/restyaboard_install.log.txt)
[restyaboard.sh.txt](https://github.com/RestyaPlatform/board/files/583387/restyaboard.sh.txt)

**Comment by lmarikannan** [comment] 2016-11-14 11:13
@Polycris If we used like this `apt-get install -y php-imagick` then it will install php5 imagick in Ubuntu 14.04 (older version). So only we have mentioned like this `apt-get install -y php7.0-imagick` to support Ubuntu older versions. Also we have checked this command in Ubuntu 16.04 `apt-get install -y php7.0-imagick`, its working fine for us. Can you please post install log to identify the problem?

**Closed by lmarikannan** 2016-11-14 11:13 UTC

**Comment by Polycris** [comment] 2016-11-18 14:52
@lmarikannan I've finished the run script install, but I also received white screen. What else can I do?

Thanks
Poly
[restyaboard_install.log.txt](https://github.com/RestyaPlatform/board/files/600158/restyaboard_install.log.txt)

**Comment by lmarikannan** [comment] 2016-11-19 06:53
@Polycris Can you please attach your nginx `/var/log/nginx/error.log` file to identify the problem?

**Comment by Polycris** [comment] 2016-11-21 12:33
@lmarikannan , this is the error.log file. Thanks for your help.
Poly
[error.log.txt](https://github.com/RestyaPlatform/board/files/603523/error.log.txt)
