### ISSUE TITLE
Can not see the comments of the card when it was moved to another list.

### ISSUE THREAD

**Issue by keky** [RestyaPlatform/board#629] opened 2016-05-04 10:19 UTC
Before：
![before](https://cloud.githubusercontent.com/assets/548338/15011454/74b93a9c-1224-11e6-907e-6ec1432b4513.png)

after:
![after01](https://cloud.githubusercontent.com/assets/548338/15011550/074deb3c-1225-11e6-9640-e40c23a819b6.png)

But if I moved it back to the previous list, The comments shown up again.
Is there any bugs here?

**Comment by rrjanbiah** [comment] 2016-05-04 11:29
@keky Probably a duplicate of #611 ?

**Comment by keky** [comment] 2016-05-04 11:56
It works for me,Thx for your help @rrjanbiah

**Comment by rrjanbiah** [comment] 2016-05-04 14:42
@keky Thanks for confirming.

**Closed by rrjanbiah** 2016-05-04 14:42 UTC
