### ISSUE TITLE
Once Move the card then close the card and we clicking back navigation, console error came

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2956] opened 2019-08-30 08:48 UTC
## Expected Behavior

Once Move the card then close the card and we clicking back navigation, console error came

## Current Behavior

Once Move the card then close the card and we clicking back navigation, console error came

## Screenshots (if appropriate):

![move_back_currentuser](https://user-images.githubusercontent.com/14290356/64007009-063ce180-cb31-11e9-819e-7104a9c70dc4.png)

**Comment by sridhar391** [comment] 2019-08-31 13:28
@srileka We are closing the issue as we are not able to reproduce the issue and feel free to re-open the issue if the issue re-occured

**Comment by sridhar391** [comment] 2019-10-30 11:43
Once Move the card then close the card and we clicking back navigation, below console error thrown

> uncaught TypeError: Cannot read property 'collection' of undefined
> 
> showCardModal: function(a) {
>         if ($("ul.dropdown-menu").parent().removeClass("open"),
>         null === this.model || _.isEmpty(this.model))
>             return !1;
>         _.isEmpty(this.model.attributes.name) || changeTitle(i18next.t("%s on %s", {
>             postProcess: "sprintf",
>             sprintf: [_.escape(this.model.attributes.name), _.escape(this.model.list.collection.board.attributes.name)]

**Closed** 2019-10-31 06:13 UTC
Labels: bug
