### ISSUE TITLE
Path to fpm socket file is hardcoded in install script

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1363] opened 2017-10-04 12:28 UTC
As per Prem, path to fpm socket file is hardcoded and so they had to modify in some instances to get it working properly

(Related #1349)

**Comment by lgg** [comment] 2018-02-13 22:25
@rrjanbiah is it fixed now?

**Comment by sridhar391** [comment] 2018-02-14 05:04
@lgg we are checking on that

**Comment by lmarikannan** [comment] 2018-03-16 07:08
@lgg @rrjanbiah Now the issue is fixed on this commit https://github.com/RestyaPlatform/board/pull/1661/commits/a16161545a3a707387fff7e2149c6a7559ff3b82

**Closed by lmarikannan** 2018-03-16 07:08 UTC
Labels: bug
