### ISSUE TITLE
Dublicate menu

### ISSUE THREAD

**Issue by iacsvrn** [RestyaPlatform/board#758] opened 2016-08-16 06:54 UTC
/ Admin CP / Settings  --> double "Cards Workflow" menu. One of then are empty.

**Comment by sampavone** [comment] 2016-08-16 09:05
Duplicate of [#755](https://github.com/RestyaPlatform/board/issues/755)

**Comment by rrjanbiah** [comment] 2016-08-17 05:39
Possible duplicate of https://github.com/RestyaPlatform/board/issues/705#issuecomment-231329066

**Comment by rrjanbiah** [comment] 2016-08-19 14:49
If this is not a duplicate of https://github.com/RestyaPlatform/board/issues/705#issuecomment-231329066 please feel free to reopen with more information.

**Closed by rrjanbiah** 2016-08-19 14:49 UTC
Labels: duplicate
