### ISSUE TITLE
Features : Paste image directly in card

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1245] opened 2017-07-13 13:47 UTC
Possibility to paste directly an image in card without attach file

**Comment by lmarikannan** [comment] 2017-09-12 06:21
@morphos88 We're tried to reproduce this issue on our demo site http://board.demo.restya.com, but we couldn't reproduced. please refer this video for more information to paste directectly an image  
[attach-image-using-copy-and-paste.webm.zip](https://github.com/RestyaPlatform/board/files/1294884/attach-image-using-copy-and-paste.webm.zip)

**Comment by rkantos** [comment] 2017-10-04 20:35
I think this is what was meant:
![Trello CTRL+V example](https://i.imgur.com/HrcbE9K.gif)

Of course it'd be expected this to work with any type of clipboard content.

**Comment by lmarikannan** [comment] 2017-10-05 05:25
@rkantos Yes. Actually this functionality is available and i.e. we have provided as video here https://www.youtube.com/watch?v=0N1L_mbb2wc. Also according to @morphos88 in this issue #1362, he mentioned that it change the user profile image. But we have tried and its working fine.

**Comment by rrjanbiah** [comment] 2017-10-05 06:12
@morphos88 may not be wrong. Reopening for him to provide further details.

**Comment by rkantos** [comment] 2017-10-05 10:57
> @rkantos Yes. Actually this functionality is available and i.e. we have provided as video here https://www.youtube.com/watch?v=0N1L_mbb2wc. Also according to @morphos88 in this issue #1362, he mentioned that it change the user profile image. But we have tried and its working fine.

See, there is an extra step here. In my example gif I don't make a click on the card that I have opened in Trello. In Trello the clipboard contents are just added when you have the card open on the browser tab and press CTRL+V. 

Personally I don't really care about this, but just pointing it out.

**Comment by ssivachidambaram** [comment] 2018-01-22 05:49
Fixed in this commit https://github.com/RestyaPlatform/board/commit/bbe6cfb7dc9d9d76b42fd13339312b91b26c912f

**Closed by ssivachidambaram** 2018-01-22 05:49 UTC
Labels: enhancement
