### ISSUE TITLE
Other user (user not a member of the board) When we trying to  open the board, "all" activities did not displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3172] opened 2019-09-19 09:59 UTC
## Expected Behavior

Other user (user not a member of the board) When we trying to  open the board, "all" activities did not displayed

## Current Behavior

Other user (user not a member of the board) When we trying to  open the board, "all" activities did not displayed

## Screenshots (if appropriate):

![all](https://user-images.githubusercontent.com/14290356/65234471-45d46900-daf2-11e9-9a65-9fb94e0ec945.png)

**Comment by sridhar391** [comment] 2019-11-20 07:34
Sometimes, for current user, "all" activities did not displayed

**Comment by sridhar391** [comment] 2019-12-02 14:09
We are closing this issue as we are not able to reproduce the issue

**Closed by sridhar391** 2019-12-02 14:09 UTC
Labels: bug
