### ISSUE TITLE
When we create the card using template, one extra field (checklist field )added (This template having only custom fields )

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3006] opened 2019-09-03 09:17 UTC
## Expected Behavior

When we create the card using template, one extra field (checklist field )added (This template having only custom fields )

## Current Behavior

When we create the card using template, one extra field (checklist field )added (This template having only custom fields )

## Screenshots (if appropriate):

![add_custom field](https://user-images.githubusercontent.com/14290356/64160505-b07e7700-ce59-11e9-9627-af0ad1468294.png)

**Comment by sridhar391** [comment] 2019-09-10 09:06
@srileka We are closing the issue as we are not able to reproduce the issue and feel free to re-open the issue if it is reocuured

**Closed by sridhar391** 2019-09-10 09:06 UTC
Labels: bug
