### ISSUE TITLE
Label deleted and edited activity is did not displayed in model card page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3143] opened 2019-09-17 12:34 UTC
## Expected Behavior

Label deleted and edited activity is did not displayed in model card page

## Current Behavior

Label deleted and edited activity is did not displayed in model card page

## Screenshots (if appropriate):

![label delete_model card](https://user-images.githubusercontent.com/14290356/65042521-a0e15100-d976-11e9-9c52-28bea7ec8444.png)

**Comment by sridhar391** [comment] 2019-09-25 14:04
@srileka We are closing this issue as we are not able to reproduce the issue, please feel free to reopen the issue if the issue occured again

**Closed by sridhar391** 2019-09-25 14:04 UTC
