### ISSUE TITLE
Sorting not working properly in checklist completed count

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2993] opened 2019-08-31 13:31 UTC
## Expected Behavior

Sorting not working properly in checklist completed count

## Current Behavior

Sorting not working properly in checklist completed count

## Screenshots (if appropriate):

![sort_checklist complete](https://user-images.githubusercontent.com/14290356/64064634-bf7ae480-cc21-11e9-8a3f-6b859643e07c.png)

**Comment by sridhar391** [comment] 2019-09-10 09:07
@srileka We are closing the issue as we are not able to reproduce the issue, feel free to reopen the issue if the issue reoccured

**Closed by sridhar391** 2019-09-10 09:07 UTC
Labels: bug
