### ISSUE TITLE
Re-ordering checklist items fail

### ISSUE THREAD

**Issue by erl4nc** [RestyaPlatform/board#2248] opened 2018-12-06 21:49 UTC
On a brand new checklist that's just created, no error occurs when re-ordering items. The below errors appear when moving a checklist item after the checklist status has changed recently.  I've observed errors, somewhat inconsistently, after:
- deleting a checklist item
- copying checklist from another card
- checking an item

postgres log:
`2018-12-06 13:29:41.635 PST [11090] ERROR:  null value in column "position" violates not-null constraint`
`2018-12-06 13:29:41.635 PST [11090] DETAIL:  Failing row contains (2513, 2018-12-06 13:29:29.260142, 2018-12-06 13:29:41.635557, 39, 1957, 343, 1, f, null).`
`2018-12-06 13:29:41.635 PST [11090] STATEMENT:  UPDATE checklist_items SET (modified, position) = ($1, $2) WHERE id = $3`

web server log:
`2018/12/06 13:29:41 [error] 1185#1185: *8188 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_query_params(): Query failed: ERROR:  null value in column &quot;position&quot; violates not-null constraint
DETAIL:  Failing row contains (2513, 2018-12-06 13:29:29.260142, 2018-12-06 13:29:41.635557, 39, 1957, 343, 1, f, null). in server/php/libs/core.php on line 2061" while reading response header from upstream, client: 172.16.40.54, request: "PUT /api/v1/boards/25/lists/281/cards/1957/checklists/343/items/2513.json?token=token HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", referrer: "/"`

## Expected Behavior
Checklists preserve order and no errors in logs

## Current Behavior
Checklists lose ordering

## Screenshots (if appropriate):
[demo video](https://github.com/RestyaPlatform/board/files/2654995/checklist-order.zip)

## Steps to Reproduce (for bugs)
The failure is somewhat inconsistent through various operations.  The one operation that seems to never preserve the item ordering:
1. Create a checklist with 3 items on a card
2. Check item 2
3. Move item 1 below item 2
4. Observe errors in logs
5. Close card
6. Reopen card
7. Items are ordered 1 2 3 instead of 2 1 3.

## Context
Failed to preserve checklist re-ordering .

## Your Environment
* Version used: 0.6.5 & 0.6.6
* Environment name and version (e.g. OS, PHP, PostgreSQL): ubuntu 16.04, php 7, postgres 9.6
* Operating System and version (desktop or mobile): desktop

**Comment by sridhar391** [comment] 2018-12-07 13:48
@erl4nc Can you please update your Restyaboard to the latest version 0.6.6 and please tell us if you are facing the same problem after updating your Restyaboard.

Please see the friendly changelog at https://restya.com/board/changelog

**Comment by erl4nc** [comment] 2018-12-11 00:11
After upgrade, my LDAP log in no longer works:

`2018/12/10 16:02:58 [error] 3875#3875: *409 FastCGI sent in stderr: "PHP message: PHP Warning:  Use of undefined constant IS_TWO_FACTOR_AUTHENTICATION_ENABLED - assumed 'IS_TWO_FACTOR_AUTHENTICATION_ENABLED' (this will throw an Error in a future version of PHP) in server/php/R/r.php on line 2437
PHP message: PHP Notice:  Undefined index: is_two_factor_authentication_enabled in server/php/R/r.php on line 2437`

It prompts me for a 2 step verification code after I enter username password, which I get no choice to opt out.  I did not receive any LDAP or ElasticSearch plugin upgrades for 0.6.6.

I also did not see any mentioning of 2 step verification/2 factor authentication in the release notes.

**Comment by sridhar391** [comment] 2018-12-11 04:48
@erl4nc We need a screen share meeting to understand the problem. please send the mail to info@restya.com

**Comment by erl4nc** [comment] 2018-12-11 16:50
What are you looking for, @sridhar391 ?  It's pretty clear to me from the error message I posted that, IS_TWO_FACTOR_AUTHENTICATION_ENABLED isn't a variable in r.php, and a quick look through the file reveals:

`if (!IS_TWO_FACTOR_AUTHENTICATION_ENABLED || $user['is_two_factor_authentication_enabled'] == 'f' || ($user['is_two_factor_authentication_enabled'] == 't' && !empty($r_post['verification_code']))) {`

Last I checked, variables start with $ in php.

**Comment by sridhar391** [comment] 2018-12-12 05:42
@erl4nc It seems to be that during the update of the Restyaboard, the upgrade SQL file named `upgrade-0.6.5-0.6.6.sql` hasn't been executed and please execute the SQL file `upgrade-0.6.5-0.6.6.sql` in the path `/usr/share/nginx/html/restyaboard/sql` on your Restyaboard database.

If you face any issue during the execution of the upgrade SQL on your Restyaboard database, please send us the error at info@restya.com .

**Comment by erl4nc** [comment] 2018-12-12 17:32
I did run the sql upgrade script (received no error) as these would show:

=# select * from setting_categories where name='Board';
 id |          created           |          modified          | parent_id | name  | description | order
----+----------------------------+----------------------------+-----------+-------+-------------+-------
 16 | 2018-12-10 15:55:53.164068 | 2018-12-10 15:55:53.164068 |           | Board |             |     6
(1 row)

=# select * from setting_categories where name='User';
 id |          created           |          modified          | parent_id | name | description | order
----+----------------------------+----------------------------+-----------+------+-------------+-------
 17 | 2018-12-10 15:55:53.165297 | 2018-12-10 15:55:53.165297 |           | User |             |     7
(1 row)

=# select * from settings where name like 'IS_TWO_FACTOR_AU%';  
 id | setting_category_id | setting_category_parent_id |                 name                 | value |                 description                 |   type   | options |                    label                    | order
----+---------------------+----------------------------+--------------------------------------+-------+---------------------------------------------+----------+---------+---------------------------------------------+-------
 81 |                  19 |                            | IS_TWO_FACTOR_AUTHENTICATION_ENABLED | true  | Is Two Way Factor Authentication is Enabled | checkbox |         | Is Two Way Factor Authentication is Enabled |     1
(1 row)

In case there were errors I didn't see, I reran the script and once again got no error except the following:
psql:upgrade-0.6.5-0.6.6.sql:35: NOTICE:  column is_two_factor_authentication_enabled already exists in users
psql:upgrade-0.6.5-0.6.6.sql:35: NOTICE:  column two_factor_authentication_hash already exists in users
psql:upgrade-0.6.5-0.6.6.sql:138: ERROR:  column users.is_intro_video_skipped does not exist
LINE 90:     users.is_intro_video_skipped,
             ^
psql:upgrade-0.6.5-0.6.6.sql:179: NOTICE:  column is_two_fdoc_image_pathactor_authentication_enabled already exists in card_attachments
psql:upgrade-0.6.5-0.6.6.sql:346: NOTICE:  column is_login_failed already exists in user_logins
psql:upgrade-0.6.5-0.6.6.sql:377: NOTICE:  column token already exists in activities
psql:upgrade-0.6.5-0.6.6.sql:449: NOTICE:  column support_list_id, support_custom_fields already exists in boards
psql:upgrade-0.6.5-0.6.6.sql:493: NOTICE:  board_id,type,custom_fields already exists in webhooks
psql:upgrade-0.6.5-0.6.6.sql:528: NOTICE:  activities_enabled already exists in webhooks

I added some debug messages for `IS_TWO_FACTOR_AUTHENTICATION_ENABLED` in config.inc.php and the error messages changed to:
`PHP message: PHP Notice:  Undefined index: is_two_factor_authentication_enabled in server/php/R/r.php on line 2437`
`PHP message: PHP Notice:  Undefined index: is_two_factor_authentication_enabled in server/php/R/r.php on line 2437" while reading response header from upstream, request: "POST /api/v1/users/login.json?token=token HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "htesttm.delta.bc.ca", referrer: "/"`
Caching issue for `IS_TWO_FACTOR_AUTHENTICATION_ENABLED`?

Back to the log in issue, 3 lines above the error (2434), `$user` is selected from `users_listing` table, which does not have `is_two_factor_authentication_enabled`.  I verified that my user in the `users` table has `f` for `is_two_factor_authentication_enabled`.  I am still stuck at the same enter two-step verification code screen.

**Comment by erl4nc** [comment] 2018-12-12 21:09
Since the first version we installed was v0.6.2, I'm wondering why `users.is_intro_video_skipped` is missing.  The column looks like it should be present from the very beginning.  Both production and test servers are missing this column and the 2 servers were built independently.  I do not know how to remedy the database without losing data at this point.

**Comment by sridhar391** [comment] 2018-12-13 05:44
@erl4nc We need a screen share meeting to understand the problem. please send the mail to info@restya.com

**Comment by erl4nc** [comment] 2018-12-13 16:33
Thank you for your offer, but I'm unable to provide you access.  We've reverted the upgrade.

**Comment by sridhar391** [comment] 2018-12-14 12:08
@erl4nc the reason for this error is that there is_intro_video_skipped column is not available in users table and users listing. so, we have to run the SQL files from v0.6.2 to the current version. but, can you please execute the below SQL  commands and tell us the result:

`DO $$ 
   BEGIN

        BEGIN
            ALTER TABLE "users" ADD COLUMN "is_intro_video_skipped" boolean NOT NULL DEFAULT 'false';
        EXCEPTION
            WHEN duplicate_column THEN RAISE NOTICE 'column is_intro_video_skipped already exists in users';
        END;
    END;
$$;`
`CREATE OR REPLACE VIEW users_listing AS
SELECT users.id,
    users.role_id,
    users.username,
    users.password,
    users.email,
    users.full_name,
    users.initials,
    users.about_me,
    users.profile_picture_path,
    users.notification_frequency,
    (users.is_allow_desktop_notification)::integer AS is_allow_desktop_notification,
    (users.is_active)::integer AS is_active,
    (users.is_email_confirmed)::integer AS is_email_confirmed,
    users.created_organization_count,
    users.created_board_count,
    users.joined_organization_count,
    users.list_count,
    users.joined_card_count,
    users.created_card_count,
    users.joined_board_count,
    users.checklist_count,
    users.checklist_item_completed_count,
    users.checklist_item_count,
    users.activity_count,
    users.card_voter_count,
    (users.is_productivity_beats)::integer AS is_productivity_beats,
    ( SELECT array_to_json(array_agg(row_to_json(o.*))) AS array_to_json
           FROM ( SELECT organizations_users_listing.organization_id AS id,
                    organizations_users_listing.name,
                    organizations_users_listing.description,
                    organizations_users_listing.website_url,
                    organizations_users_listing.logo_url,
                    organizations_users_listing.organization_visibility
                   FROM organizations_users_listing organizations_users_listing
                  WHERE (organizations_users_listing.user_id = users.id)
                  ORDER BY organizations_users_listing.id) o) AS organizations,
    users.last_activity_id,
    ( SELECT array_to_json(array_agg(row_to_json(o.*))) AS array_to_json
           FROM ( SELECT boards_stars.id,
                    boards_stars.board_id,
                    boards_stars.user_id,
                    (boards_stars.is_starred)::integer AS is_starred
                   FROM board_stars boards_stars
                  WHERE (boards_stars.user_id = users.id)
                  ORDER BY boards_stars.id) o) AS boards_stars,
    ( SELECT array_to_json(array_agg(row_to_json(o.*))) AS array_to_json
           FROM ( SELECT boards_users.id,
                    boards_users.board_id,
                    boards_users.user_id,
                    boards_users.board_user_role_id,
                    boards.name,
                    boards.background_picture_url,
                    boards.background_pattern_url,
                    boards.background_color
                   FROM (boards_users boards_users
                     JOIN boards ON ((boards.id = boards_users.board_id)))
                  WHERE (boards_users.user_id = users.id)
                  ORDER BY boards_users.id) o) AS boards_users,
    users.last_login_date,
    li.ip AS last_login_ip,
    lci.name AS login_city_name,
    lst.name AS login_state_name,
    lco.name AS login_country_name,
    lower((lco.iso_alpha2)::text) AS login_country_iso2,
    i.ip AS registered_ip,
    rci.name AS register_city_name,
    rst.name AS register_state_name,
    rco.name AS register_country_name,
    lower((rco.iso_alpha2)::text) AS register_country_iso2,
    lt.name AS login_type,
    to_char(users.created, 'YYYY-MM-DD"T"HH24:MI:SS'::text) AS created,
    users.user_login_count,
    users.is_send_newsletter,
    users.last_email_notified_activity_id,
    users.owner_board_count,
    users.member_board_count,
    users.owner_organization_count,
    users.member_organization_count,
    users.language,
    (users.is_ldap)::integer AS is_ldap,
    users.timezone,
    users.default_desktop_notification,
    users.is_list_notifications_enabled,
    users.is_card_notifications_enabled,
    users.is_card_members_notifications_enabled,
    users.is_card_labels_notifications_enabled,
    users.is_card_checklists_notifications_enabled,
    users.is_card_attachments_notifications_enabled,
    users.is_intro_video_skipped,
    users.is_invite_from_board,
    users.is_two_factor_authentication_enabled
   FROM (((((((((users users
     LEFT JOIN ips i ON ((i.id = users.ip_id)))
     LEFT JOIN cities rci ON ((rci.id = i.city_id)))
     LEFT JOIN states rst ON ((rst.id = i.state_id)))
     LEFT JOIN countries rco ON ((rco.id = i.country_id)))
     LEFT JOIN ips li ON ((li.id = users.last_login_ip_id)))
     LEFT JOIN cities lci ON ((lci.id = li.city_id)))
     LEFT JOIN states lst ON ((lst.id = li.state_id)))
     LEFT JOIN countries lco ON ((lco.id = li.country_id)))
     LEFT JOIN login_types lt ON ((lt.id = users.login_type_id)));`

**Comment by erl4nc** [comment] 2019-02-07 23:12
Bug is present in 0.6.6.

**Comment by ssivachidambaram** [comment] 2019-02-11 08:13
@erl4nc Reopening this issue as we can able to reproduce it.

**Comment by erl4nc** [comment] 2019-02-12 17:22
Do you have a rough date on when 0.6.7 with the fix is planned to be released?  Is there a release calendar I could follow?

**Comment by JtheBAB** [comment] 2019-02-12 17:31
Just add

https://github.com/RestyaPlatform/board/commit/836cd0634a5cfbf876c19d6a1c1a70786c7a04a8

And you have the fix.

**Comment by erl4nc** [comment] 2019-02-12 17:40
Asides from the fact that I'm not interested in building the app myself, I would still not mind knowing if there's a release calendar.

> Just add
> 
> [836cd06](https://github.com/RestyaPlatform/board/commit/836cd0634a5cfbf876c19d6a1c1a70786c7a04a8)
> 
> And you have the fix.

**Comment by JtheBAB** [comment] 2019-02-12 17:55
You dont need to build the app. Just add this line there and you have the fix

**Comment by erl4nc** [comment] 2019-02-12 18:02
> You dont need to build the app. Just add this line there and you have the fix

Where would you like me to add the line? 

`
$ ls client/js/
authorize.cache.js  default.cache.b41fdf50.js  workflow_templates
$ 
`

**Comment by JtheBAB** [comment] 2019-02-13 08:42
I am sorry. I was sure that this is in that default file but i can't find it. Shame on me.

**Comment by sridhar391** [comment] 2019-02-16 04:13
@JtheBAB please download the zip file and unzip it in your Restyaboard folder `/usr/share/nginx/html/restyaboard` and after unzipping the file. please clear the cache in your browser and refresh the page to see the changes 
[checklist_item_position_sort.zip](https://github.com/RestyaPlatform/board/files/2871587/checklist_item_position_sort.zip)

**Comment by erl4nc** [comment] 2019-02-19 17:17
@sridhar391 Do you have a rough date on when 0.6.7 with the fix is planned to be released? Is there a release calendar I could follow?

I filed [another issues](https://github.com/RestyaPlatform/board/issues/2247) at the same time as this one.  I would prefer to have both fixes.

**Comment by sridhar391** [comment] 2019-02-21 04:54
@erl4nc we are working on the v0.6.7 (Boney M) and we will release soon and for `Database errors in log` issue, we have fixed the issue in the commit https://github.com/RestyaPlatform/board/commit/61f4cda9f4dedad25dbe4accb604b5fd9da26fae

**Comment by erl4nc** [comment] 2019-02-21 21:59
> @erl4nc we are working on the v0.6.7 (Boney M) and we will release soon and for `Database errors in log` issue, we have fixed the issue in the commit [61f4cda](https://github.com/RestyaPlatform/board/commit/61f4cda9f4dedad25dbe4accb604b5fd9da26fae)

Is that commit included in below?
> @JtheBAB @erl4nc please download the zip file and unzip it in your Restyaboard folder `/usr/share/nginx/html/restyaboard` and after unzipping the file. please clear the cache in your browser and refresh the page to see the changes
[checklist_item_position_sort.zip](https://github.com/RestyaPlatform/board/files/2871587/checklist_item_position_sort.zip)

**Comment by sridhar391** [comment] 2019-02-22 04:22
@erl4nc For [Database errors in log issue](https://github.com/RestyaPlatform/board/issues/2247), please add the line ` unset($r_post['checklist_items']);` after `line 4902` of the `r.php` file in the `/usr/share/nginx/html/restyaboard/server/php/R` folder like https://github.com/RestyaPlatform/board/blob/master/server/php/R/r.php#L4902

**Comment by rrjanbiah** [comment] 2019-05-15 14:39
Failed to preserve checklist sorting reoccurred in Boney M. Reported by Steve

**Comment by rrjanbiah** [comment] 2019-05-20 09:01
Additional note:

Checklist sorting gets quirky when its count reaches 10 (till then, it seems to work good)

**Comment by mdicamillo** [comment] 2019-11-03 13:49
Besides reordering, I am seeing that one of the items on the checklist changes its content to be a duplicate of the last item on the checklist. This does not seem to be dependent on the length of the checklist. It happens on checklists with 3 items to 11 items.

**Comment by sridhar391** [comment] 2019-11-04 04:45
@mdicamillo Can you please tell us if your Restyaboard version is v0.6.7 and you can check your Restyaboard version by clicking the user image icon in the footer and click the "About Restyaboard" option like the attached image "about_restyaboard_option.png" and in the About page check the Restyaboard version like the attached image "restyaboard_version.png"

![about_restyaboard_option](https://user-images.githubusercontent.com/17172525/68100065-eee0f280-feeb-11e9-8ccd-76529c73ffca.png)
![restyaboard_version](https://user-images.githubusercontent.com/17172525/68100066-ef798900-feeb-11e9-8bce-eb1a2bd7dbff.png)

**Comment by mdicamillo** [comment] 2019-11-04 06:16
Still on v0.6.6 does v0.6.7 fix this issue?

**Comment by sridhar391** [comment] 2019-11-04 06:39
@mdicamillo Yes, we have fixed that issue in v0.6.7 (Boney M) and please update to Restyaboard v0.6.7 (Boney M) for the issue fix.

**Comment by sridhar391** [comment] 2019-11-12 06:11
We are closing this issue as there is no activity and please feel free to reopen the issue if the issue occurred in the Restyaboard v0.6.7 (Boney M)

**Closed by sridhar391** 2019-11-12 06:11 UTC
Labels: bug
