### ISSUE TITLE
In list view, counts are wrong

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1050] opened 2017-02-23 12:35 UTC
(From one of our customer) counts displayed in list view are different from grid view.

(Not tested)

**Comment by lmarikannan** [comment] 2017-03-17 11:51
@rrjanbiah Could not reproduce this issue. Closing this for now. If you get any other issues related this, please feel free to reopen.

**Closed by lmarikannan** 2017-03-17 11:51 UTC
Labels: bug
