### ISSUE TITLE
Checklist Weird Behavior

### ISSUE THREAD

**Issue by theshades** [RestyaPlatform/board#1190] opened 2017-05-23 23:04 UTC
Any time I have more than one checklist, it always puts my text in the last checklist initially, even if I add it to the first one.

**Comment by lmarikannan** [comment] 2017-05-31 12:52
@theshades We checked about this issue in our local, but we could not reproduce this issue. Could you please double check this. If this issue will reproduce, please explain about that case to reproduce.

**Comment by llavall** [comment] 2017-05-31 13:22
Just checked in our local version - here it works as expected.

**Comment by lmarikannan** [comment] 2017-07-24 06:08
@theshades Closing due to inactivity. Please feel free to reopen when you have more information

**Closed by lmarikannan** 2017-07-24 06:08 UTC
