### ISSUE TITLE
User added custom fields are not updated in list view

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2936] opened 2019-08-29 11:20 UTC
## Expected Behavior

User added custom fields are not updated in list view

## Current Behavior

User added custom fields are not updated in list view

## Screenshots (if appropriate):

![custom field_list](https://user-images.githubusercontent.com/14290356/63936265-07143b80-ca7d-11e9-863e-75b8969a6775.png)

**Comment by sridhar391** [comment] 2019-08-30 05:55
@srileka Closing this issue because it is not able to reproduce and if the issue reproduced, feel free to re-open the issue

**Closed** 2019-11-01 05:04 UTC
Labels: bug
