### ISSUE TITLE
LDAP example

### ISSUE THREAD

**Issue by zijam** [RestyaPlatform/board#79] opened 2015-10-12 13:47 UTC
Is there any LDAP example for RestyaBoard? I have currently problem with using our internal AD for authentication of users. 

What is '**_User DNS**_" ? 

In the **Domain** field, should I type the path to our users in AD?

**Comment by rrjanbiah** [comment] 2015-10-12 15:06
@zijam Yes this definitely needs proper documentation. For now, please see if this example is helpful, if not, please reply:

     Server
       ldap://192.168.1.25
     Port
       389
     Protocol Version
       3
     User DNS
        ou=mycompany,dc=mycompany,dc=in
     Organization
     
     Domain
       sAMAccountName
     Username
       admin
     Password
       adminpass

**Comment by akhasis** [comment] 2016-01-25 12:55
I don't know if the example refers to an older version or I'm doing something wrong, but at the Login configuration tab I don't get the fields you mention. Mine are:

== Enabled login options ==
* Standard
* Ldap

== LDAP Configuration ==
=== Server details ===
Server
Port
Protocol version
Root dn
Organization

=== Connection details ===
Uid field
Bind dn
Bind password

I am quite unexperienced at configuring LDAP and I tried many different configurations. Always got a success message ("settings updated successfully") but wasn't able to login with a user from my Active directory. Could you please provide an example? 

I'm trying to log against a Windows 2003 server, If I could find the Restyaboard version I would let you know, but for now I can only tell you that it was installed on January 15th, and was the last version then.

Thank you in advance.

**Comment by rrjanbiah** [comment] 2016-01-25 13:10
@akhasis You may find the Restyaboard version by visiting about page at \#about (Click Restyboard icon in the bottom-left corner)

Sorry for the trouble you're having with LDAP. We changed labels for them to be as in other popular applications. So, now, sample configuration would be:

     Server
       ldap://192.168.1.25
     Port
       389
     Protocol Version
       3
     Root dn
        ou=mycompany,dc=mycompany,dc=in
     Organization
     
     Uid field
       sAMAccountName
     Bind dn
       admin
     Bind password
       adminpass

**Comment by rrjanbiah** [comment] 2016-01-25 15:26
@akhasis Keeping this open till you respond.

**Comment by raphaelcasimir** [comment] 2016-01-27 15:07
I'm using phpldapadmin and I do not know how to organise my new ldap database to be usable with retyaboard. And I can't see any documentation about this... Could you please give me some advices ?

**Comment by rrjanbiah** [comment] 2016-01-27 15:16
@raphaelcasimir phpldapadmin is one of many frontend tools available to manage records in LDAP server. 

Configuration as shown in https://github.com/RestyaPlatform/board/issues/79#issuecomment-174504477 will enable Restyaboard to connect with your LDAP server. It is nothing to do with phpldapadmin.

If you meant something else, please rephrase. Thanks

**Comment by raphaelcasimir** [comment] 2016-01-27 15:49
I meant that the config seems to be quite specific, if "cn=admin,dc=example,dc=org" is my admin user but the users are stored in the "ou=users" do I just need to put "admin" as the Bind dn and "ou=users,dc=example,dc=org" as the root dn ? If it is the case, it doesn't seem to work.

It doesn't send any error message back, when validating settings or trying to connect to the app with a LDAP database user.

**Comment by raphaelcasimir** [comment] 2016-01-27 15:50
An what is the password encryption ? Clear? md5? sha...
I think it needs some more documentation

**Comment by rrjanbiah** [comment] 2016-01-27 15:56
@raphaelcasimir Currently we're using same terminology that are been used in LDAP supported software applications. So, we're not exactly sure what to improve here. Anyway, we'll think about it.

Do you think, if this link http://serverfault.com/questions/616698/in-ldap-what-exactly-is-a-bind-dn is helpful to interpret the terminology and configure it right?

**Comment by rrjanbiah** [comment] 2016-01-27 15:57
@raphaelcasimir There's no validation in settings page. It only saves the configuration. We can see what we can do for that.

**Comment by raphaelcasimir** [comment] 2016-01-27 16:25
It can be helpful, yes, but I think I have understood the principle. The problem is that we do not have any log to check what's wrong. Or have we ? (I'm working with docker)

Do you kow about the password encryption as well ?

**Comment by akhasis** [comment] 2016-01-27 18:21
Sorry, I wasn't able to check your answer sooner. Thanks to your example I have been able to configure LDAP and Restyaboard is working great. 

Keep up the great work!

**Comment by rrjanbiah** [comment] 2016-01-27 19:57
@akhasis That's so nice to hear. Thanks for updating.

**Comment by rrjanbiah** [comment] 2016-01-27 20:00
@raphaelcasimir 

> It can be helpful, yes, but I think I have understood the principle. The problem is that we do not have any log to check what's wrong. Or have we ? 

PHP errors can be logged through ``php.ini`` settings. But, I think, adding a "Test LDAP" button would suffice to test (?).

> (I'm working with docker)

Unless you have special reasons to use docker, we suggest our new install script for all Linux based installations http://restya.com/board/install.html#Installscript

> Do you know about the password encryption as well ?

No encryption.

**Comment by raphaelcasimir** [comment] 2016-01-27 21:38
Ok thanks for the help I'll figure out the problem and post the answer if I decide to continue with ldap.

**Comment by rrjanbiah** [comment] 2016-01-28 08:57
@raphaelcasimir Sure, please keep us posted.

**Comment by raphaelcasimir** [comment] 2016-02-01 11:08
I have tried a tcpdump on my ldap docker container, but it shows nothing when I'm trying to connect with restya. Though it works well with the other app, phpldap admin.
If you see anything wrong...
![ldaprestya](https://cloud.githubusercontent.com/assets/9111357/12715760/6420b732-c8dc-11e5-983d-15394d72e6be.png)
Sorry for the inconvenience if I was doing wrong from the beginning

**Comment by rrjanbiah** [comment] 2016-02-01 11:33
@raphaelcasimir Sorry, we don't have good expertise in docker. If we're right, connection to outside of docker container may not work. Please check with experts.

**Comment by rrjanbiah** [comment] 2016-02-05 08:38
Good LDAP Guide from Antti Hurme in https://groups.google.com/d/msg/restya/HOzaJEmCEJ4/T-itiwOXBAAJ

**Comment by ssivachidambaram** [comment] 2016-02-19 13:35
Changed labels and given help tip for LDAP settings to configure easily.

**Comment by mistajolly** [comment] 2016-05-09 08:52
Since this is an Admin panel, it would be good to have more verbose messages and also be able to test the LDAP login from this page.

**Comment by fwolfst** [comment] 2016-10-04 13:47
I agree on issues with
1) the verbosity of the messages (is "User records not found" better than "LDAP connection failed"? What means what?)
2) Unclarity what to enter in the text inputs ("v3" or "3", "ldap://192.168.1.11" or "192...."?), which could relatively simply be improved by an improved help text
3) debuggibility. A "test" button and/or location of a log file with relevant entries would be great.

Thanks so far! I was not yet able to get my installation working with a pretty standard openldap setup.

**Comment by fwolfst** [comment] 2016-10-04 14:28
I will not be able to spend a lot of time, but if somebody provides me with a one-liner how I can output some debug message (into nginx or php log file), I could invest some minutes into checking what happens in `core.php#ldapAuthenticate` and debug my issue (openldap/posixAccount).

**Comment by rrjanbiah** [comment] 2016-10-04 14:46
@fwolfst Not sure, if you're asking PHP's `error_log()` function http://php.net/manual/en/function.error-log.php

**Comment by fwolfst** [comment] 2016-10-04 14:56
Well I got the log-in functionality working. What actually did not (yet) work is the "import users" function.

**Comment by fwolfst** [comment] 2016-10-04 15:01
And I do not get the architecture by skimming through the source files. Where would I have to search for the code actually executed by click on "Import users"?

**Comment by rrjanbiah** [comment] 2016-10-04 15:05
@fwolfst It is here https://github.com/RestyaPlatform/board/blob/master/server/php/R/r.php#L2951 

Yes, code refactoring is in pipeline.

**Comment by fwolfst** [comment] 2016-10-04 15:11
Ok, so to me it looks as if the "Import users" process ignores the settings for user filter/attribute and assumes ActiveDirectory Style. For example in my case instead of `samaccountname` `uid` should be used (which can be configured in the ldap configuration) - but I might be mistaken.

**Comment by lmarikannan** [comment] 2017-01-13 06:13
@fwolfst Fixed in this commit https://github.com/RestyaPlatform/board/pull/959

**Closed by lmarikannan** 2017-01-13 06:13 UTC
