### ISSUE TITLE
i can get nothing

### ISSUE THREAD

**Issue by zukizukki17** [RestyaPlatform/board#635] opened 2016-05-06 07:06 UTC
hi
i can't see anything on the web browser(chrome) 
i have no idea why it doesn't work 

i use centOS 6.5

i got two errors from chrome's developer tool
i write them below

[1st error]
http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:4 GET
http://admin:restya@133.162.219.107/api/v1/oauth.json?_=1462517448694 404 (Not Found)
send @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:4
$.extend.ajax @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:4
b.ajax @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:12
b.sync @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:12
h @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:13
d @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:13
Backbone.sync @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:72
c.extend.sync @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:12
c.extend.fetch @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:12
App.ApplicationView.Backbone.View.extend.initialize @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:55
b.View @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:12
d @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:13
d @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:13
d @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:13
Backbone.Router.extend.login @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:72
c.extend.execute @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:12
(anonymous function) @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:12
(anonymous function) @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:12
(anonymous function) @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:12
o.each.o.forEach @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:11
o.some.o.any @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:12
c.extend.loadUrl @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:12
c.extend.start @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:12
(anonymous function) @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:72

[2nd error]
VM723:1 
Uncaught SyntaxError: Unexpected token < in JSON at position 0
(anonymous function) @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:72
o @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:13
d.error @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:13
l @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:1
m.fireWith @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:1
d @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:4
d @ http://admin:restya@133.162.219.107/restyaboard/client/js/default.cache.a331c8c3.js:4

could you help me about this problem?

**Comment by juancarbone** [comment] 2016-05-06 18:56
exist an mail address to access via web? Thanks

**Comment by zukizukki17** [comment] 2016-05-07 09:48
you mean URL??
i narrow the sorce IPaddress with firewall

**Comment by juancarbone** [comment] 2016-05-07 19:45
Thank you! Sorry for my english. when i put the ip adress of my server, load the icon of rastyaboard in the tab, but the screen contining in blank. i think a problen in the conection to the db or php configuration, but i dont know.

**Comment by ssivachidambaram** [comment] 2016-05-09 07:08
@zukizukki17 While checking the error log, it looks like you are accessing the site like this `http://admin:restya@133.162.219.107/restyaboard/client`. Can you please change the root values in `restyaboard.conf` file?

https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf#L5
`root /usr/share/nginx/html/restyaboard;`

https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf#L29
`root /usr/share/nginx/html/restyaboard/client;`

https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf#L42
`root /usr/share/nginx/html/restyaboard/client;`

And then restart the nginx and try it like this `http://admin:restya@133.162.219.107/`.

**Comment by zukizukki17** [comment] 2016-05-10 01:12
@juancarbone 
thank you for your advice.
i'm going to check configuartion of php and db.

@ssivachidambaram 
i checked  restyaboard.conf  and it have already correct.
i accessed  http://admin:restya@133.162.219.107/ .
i found below 

<img width="915" alt="screenshot_20160510" src="https://cloud.githubusercontent.com/assets/9434168/15132588/4d37f546-1696-11e6-8bf6-2e4093ce3c1b.png">

**Comment by ssivachidambaram** [comment] 2016-05-10 08:01
@zukizukki17 Can you please attach your `restyaboard.conf` and nginx `error.log` to understand more about the issue?

**Comment by zukizukki17** [comment] 2016-05-10 11:11
@ssivachidambaram 
this is restyaboard.conf
[restyaboard.conf.txt](https://github.com/RestyaPlatform/board/files/257018/restyaboard.conf.txt)

**Comment by zukizukki17** [comment] 2016-05-10 11:12
@ssivachidambaram 
this is nginx error.log
[error.log.txt](https://github.com/RestyaPlatform/board/files/257024/error.log.txt)

**Comment by ssivachidambaram** [comment] 2016-05-10 13:13
In your configuration file, server_name was not replaced. It displays as `server_name _;`. Can you please provide your domain name (e.g., www.example.com, 192.xxx.xxx.xxx, etc.,)? Also can you please attach your install log?

**Comment by zukizukki17** [comment] 2016-05-11 01:55
@ssivachidambaram 
thanks for your advice. i confirm domain name.

and this is restyaboard_install.log
[restyaboard_install.log.txt](https://github.com/RestyaPlatform/board/files/258443/restyaboard_install.log.txt)

**Comment by ssivachidambaram** [comment] 2016-05-12 09:40
@zukizukki17 Can you please confirm whether its working for you after changed the server_name or still do you have problem?

Related to #630.

**Comment by zukizukki17** [comment] 2016-05-12 14:31
@ssivachidambaram 
I'm sorry to be late to answer.
I still have this problem.

I think "server_name" is IP address "133.162.219.107". Is it strange?
if it is strange, can you teach me how to change the "server_name".

**Comment by ssivachidambaram** [comment] 2016-05-12 14:46
@zukizukki17 Can you please change the `server_name _;` to `server_name 133.162.219.107;` in `restyaboard.conf` then restart nginx and try?

**Comment by ssivachidambaram** [comment] 2016-05-14 04:57
@zukizukki17 Can you please move `/etc/nginx/sites-enabled/default` to `/etc/nginx/default` and try? Because if you are accessing through IP its taking the nginx default configuration.

**Comment by zukizukki17** [comment] 2016-05-15 08:08
@ssivachidambaram 
i changed server_name.
but there is not /etc/nginx/sites-enabled/default.

**Comment by rrjanbiah** [comment] 2016-05-15 11:05
@zukizukki17 In that case, can you please mention your directory structure?

**Comment by rrjanbiah** [comment] 2016-05-19 06:34
@zukizukki17 Are you able to resolve it yet?

**Comment by lmarikannan** [comment] 2016-05-26 05:42
@zukizukki17 We are waiting for your reply

**Comment by lmarikannan** [comment] 2016-06-10 06:57
@zukizukki17 Closing due to inactivity. Please feel free to reopen when you have more information

**Comment by DavidJares** [comment] 2016-06-15 11:21
Hi, I have exactly the same problem, triend every option here. Only thing that loads is favicon and progresbar. Entire page is blank (white).

**Comment by rrjanbiah** [comment] 2016-06-15 11:55
@DavidJares Can you attach install log?

**Comment by DavidJares** [comment] 2016-06-15 11:59
Should I anonymize it a little bit? Plus it is all in czech language -.- my friend prepared the ubuntu server in czech :(

**Comment by rrjanbiah** [comment] 2016-06-15 12:07
@DavidJares Yes, please remove any sensitive information. Language string is OK

**Comment by DavidJares** [comment] 2016-06-15 12:12
Ok here it is (found only DB password):
http://pastebin.com/nQch8WRT

**Comment by rrjanbiah** [comment] 2016-06-15 12:41
@DavidJares Looks like a typical duplicate of #685 Not sure why in Ubuntu it breaks now. 

So, closing this and will follow #685

**Closed by rrjanbiah** 2016-06-15 12:41 UTC
