### ISSUE TITLE
When we finding parent and child card, all the cards in the current board should be display

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3162] opened 2019-09-18 12:51 UTC
## Expected Behavior

When we finding parent and child card, all the cards in the current board should be display

## Current Behavior

When we finding parent and child card, all the cards in the current board should be display

## Screenshots (if appropriate):

![parent_all cards](https://user-images.githubusercontent.com/14290356/65150148-1ade0c80-da41-11e9-98dc-c5181a3d0598.png)

**Comment by jawahar336** [comment] 2019-10-01 11:47
@srileka  we are closing this issue as the issue is not reproduced and please feel free to reopen the issue if it occured again

**Closed by jawahar336** 2019-10-01 11:47 UTC
Labels: bug
