### ISSUE TITLE
Reply via email responses appears in description space instead of normal reply space 

### ISSUE THREAD

**Issue by praburaj06** [RestyaPlatform/board#643] opened 2016-05-19 05:53 UTC
whenever we reply to a card through the notification mail ,the reply content is no shown in the description (please refer the image below)  instead of its regular place..if you have any ideas please let me know
![email reply error screen](https://cloud.githubusercontent.com/assets/6758233/15383877/0d3eeb1e-1db4-11e6-9f37-d420e621b7fd.png)

**Comment by rrjanbiah** [comment] 2016-05-19 05:58
@praburaj06 Thanks for reporting this. We'll check and update.

**Comment by praburaj06** [comment] 2016-05-19 06:58
We have done a fresh installation of Restyabord in our cloud platform and there also the reply for email notifications are displayed in description only & if there is multiple reply's via email notifications the older reply's are overridden by the newer ones...therefore it effectivly shows only the latest reply via email content in the description space.

**Comment by rrjanbiah** [comment] 2016-05-19 12:25
@praburaj06 Yes, this could be an issue. We'll check and fix.

**Comment by rrjanbiah** [comment] 2016-05-20 14:44
@praburaj06 We're working on this issue and fill push fix soon.

**Comment by praburaj06** [comment] 2016-05-23 14:02
First of all i would like to thank you for your quick support & your hard-work but after updating this imap.php file the comments are not at all appearing in my board,do i have to do any changes elsewhere ??

**Comment by rrjanbiah** [comment] 2016-05-23 14:24
@praburaj06 Thanks for your note. We'll check before we close this issue.

**Comment by praburaj06** [comment] 2016-05-30 12:12
Guys ...Is this code working ???

**Comment by rrjanbiah** [comment] 2016-05-30 12:17
@lmarikannan FYI

**Comment by praburaj06** [comment] 2016-06-02 11:10
Guys thanks lot ,
this code is working fine except that for each & every reply two entries shown the reply board... 
![image](https://cloud.githubusercontent.com/assets/6758233/15743082/aae4a052-28e0-11e6-84f3-8b355ef5424f.png)

**Comment by lmarikannan** [comment] 2016-06-02 11:15
We'll check and fix.

**Comment by praburaj06** [comment] 2016-06-02 11:24
Thanks...

**Comment by lmarikannan** [comment] 2016-06-11 05:47
@praburaj06 We have tried to reproduce this issue in local but we cannot able to reproduce it.

**Comment by praburaj06** [comment] 2016-06-13 04:51
ok...i'll check it out & let you know....

**Comment by praburaj06** [comment] 2016-06-16 09:15
I've checked and some of the reply's appearing with duplication's  & most of them are not at all appearing ....

**Comment by lmarikannan** [comment] 2016-06-16 11:10
@praburaj06  Can you please find that case to reproduce?

**Comment by lmarikannan** [comment] 2016-06-16 11:10
Closing this for now. If you get any issues, please feel free to reopen.

**Closed by lmarikannan** 2016-06-16 11:10 UTC

**Comment by praburaj06** [comment] 2016-06-16 11:26
I don't think this issue is fixed ,but thanks for your support & quick response.
