### ISSUE TITLE
Can't add local user when LDAP login is enabled

### ISSUE THREAD

**Issue by nicolas-r** [RestyaPlatform/board#692] opened 2016-06-22 10:35 UTC
Hi

I don't if this is by design or not, but after enabling "LDAP" in "Enabled Login Options", the option to add an user in the "Admin CP / Users" is no more present.

I have a need to have both local and ldap users, can you tell me if this possible or not ?

Regards

Nicolas

**Comment by rrjanbiah** [comment] 2016-06-23 12:52
@nicolas-r Currently it is by design. Will check and update.

**Comment by nicolas-r** [comment] 2016-06-23 16:23
OK. i have solve my problem by disabling LDAP login temporarly, add my local user and enable LDAP again

**Comment by Adysone** [comment] 2016-11-22 09:27
@nicolas-r How did you disable LDAP login? If I uncheck the "LDAP" box and I save, when I come back to the settings, the box is checked again.

**Comment by nicolas-r** [comment] 2016-11-23 09:41
I just uncheck the LDAP box and click on the save or submit button, nothing more

**Comment by Polycris** [comment] 2016-12-01 12:42
Hi, guys!  I had the same problem... I had LDAP enabled once time and later I could not disable it anymore, the box is always checked. I need disable this option to add my local user. 
Thanks!
Poly

**Comment by lmarikannan** [comment] 2017-01-12 05:51
Fixed in this commit https://github.com/RestyaPlatform/board/commit/3ad042dd0ff36df1ba16b63563af455bf6cc85b7

**Closed by lmarikannan** 2017-01-12 05:51 UTC
